---
title: "About"
menu: main
output: html_document
weight: -210
tags: [about]
comments: false
---

I'm a data scientist living in Antwerp (Belgium) with a background in evolutionary biology. During my PhD in eco-evolutionary dynamics I discovered my interest in programming. After a short detour in Delphi Pascal I started working with Python and got hooked fast. For my research I built a variety of individual based simulation models producing a lot of data along the way. This data was analysed using R, a programming language I was first introduced to during a statistics course in 2007. After my PhD (2015) I decided to follow my interest in programming and data analysis and started working at a [software firm](https://www.cobundu.com/) that specializes in smart building / IoT applications. During my time there my activities included: gathering and pre-processing data from [Hadoop](http://hadoop.apache.org/) using R interfaces for [Spark](https://spark.rstudio.com/) and [Impala](https://github.com/ianmcook/implyr), data [tidying](http://tidyr.tidyverse.org/) and [wrangling](http://dplyr.tidyverse.org/), building models, visualizing data with [ggplot2](http://ggplot2.tidyverse.org/), [leaflet](https://rstudio.github.io/leaflet/), and building dashboards using [Shiny](https://shiny.rstudio.com/).
After 3 years of wrangling sensor data I felt the need to expand my machine learning knowledge and joined the aplied AI startup [Faktion](https://www.faktion.com/). At Faktion I switched back to Python I'm excited to build experience working with Jupyter, Pandas, scikit-learn in a team of machine learning experts.

Why blog?
=========

As an open source software user I've profited enormously from the public work of others. With this blog I hope to do my part in contributing to the wonderful open source community.

About This Site
=========

This blog is built with [blogdown](https://github.com/rstudio/blogdown) and [Hugo](https://gohugo.io/), with the [Minimo](https://github.com/MunifTanjim/minimo) theme. I deploy my blog using [Netlify](https://netlify.com/). 

While creating this website I used the blogs of [Julia Silge](https://juliasilge.com) and [David Robinson](http://varianceexplained.org/) as points of reference. If you haven't already seen their work, go check it out, it's awesome.

All blog posts are released under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).