---
title: "Resume"
menu: main
output: html_document
weight: -210
tags: [resume]
comments: false
---

### Profile

I enjoy getting insights out of data using programming tools. During my PhD, I've learned how to approach complex problems and communicate the results to both expert and non-expert audiences. I have strong data wrangling and visualization skills and typically come up with first results sooner than expected. I'm always keen to expand my technical toolkit and learn new concepts to get more angles while tackling a problem.


### Tools

* Python (Monte Carlo individual-based simulations, Pandas, sklearn, Pytorch...)
* R (Tidyverse adept, sparklyr, Rmarkdown, ...)
* SQL (PostgreSQL, Impala, TimescaleDB, MSSQL, Postgis)
* MongoDB
* Databricks
* Spark (SparkSQL, streaming)
* Docker

### Experience


##### Head of Machine Learning, [Faktion](https://www.faktion.com/)
2021-Present

I'm leading a team of amazing ML engineers on a mission to bring value to our customers using data. We use Computer Vision, Reinforcement Learning, and Natural Language Processing to reach that goal. I work closely with our HR team to recruit the best talent.

##### Machine learning engineer & head of ML education, [Faktion](https://www.faktion.com/)
2018-2020

Datacamp instructor:

* [Dimensionality reduction in Python](https://www.datacamp.com/courses/dimensionality-reduction-in-python)
* [Reshaping data with tidyr](https://www.datacamp.com/courses/reshaping-data-with-tidyr)

Intro to ML course:
* Full day [Machine Learning 101 Using Python](https://github.com/jeroenboeye/ml-tutorial) workshop at the 2019 [MLConference](https://mlconference.ai/) in Berlin.

Sensor data analysis:

* Building condition classifiers for high throughput telemetry sensor data.
* Setting up machine learning pipeline within lambda architecture.
* Anomaly detection pipeline for well-being of elders using infra-red motion sensors.
* Forecasting electricity and natural gas usage for hundreds of customers.
* Yield optimization and root-cause analysis of an industrial polymerization process.

Sales analytics:

* Product recommendation engine
* Time series forecasts (ARIMA)
* Customer segmentation
* Propensity model

Computer vision:

* Damage detection on air freight containers.
* Solar panel detector from aerial images (Dockerized PostgreSQL + PostGIS database for aerial image pre-processing -> Microsoft Azure custom vision API)
* Winner of the [2018 Vinci Energies Hackathon](https://www.faction.xyz/human-activity-capturer-and-klassifier-wins-first-prize-at-vinci-energies-hackathon/) detecting emergency situations from video data

Consulting:

* AI maturity assessment 
* AI strategy development

##### Data Scientist, [MCS solutions](https://www.mcssolutions.com/)
2015-2018
 
Sensor data analysis:

* Combining data sets from multiple sources (Hadoop, Oracle, local files (xml, csv, json, excel...))
* Building R-packages
* Tailoring visualizations for any data set
* Building interactive dashboards
* Getting actionable insights from data and report to clients
* Setting up logging and email alerts for scheduled analyses
* Forecasting comfort conditions (CO2, temperature, humidity)
* Forecasting battery drainage
* Applying a range of machine learning techniques ([Random forests](https://en.wikipedia.org/wiki/Random_forest), [GLM](https://en.wikipedia.org/wiki/Generalized_linear_model), [PCA](https://en.wikipedia.org/wiki/Principal_component_analysis), [Clustering](https://en.wikipedia.org/wiki/K-means_clustering), regression, [Anomaly detection](https://en.wikipedia.org/wiki/Anomaly_detection),...) + Experiment with neural nets

Custom analyses:

* Vulnerability assessment of global supply chain
* Optimize office layout based on employee activities
* Geo-tagging addresses and spatial analysis
* Survey analysis

##### PhD student, [Ghent University](http://www.ecology.ugent.be/terec/)
2011-2015
 
Building complex individual-based Monte Carlo models in a spatial context (using Python) and run them on [High Performance Computing infrastructure](https://www.ugent.be/hpc/en). Scientific writing and talks. Mentoring students during their Master thesis and teaching. International collaborations.

### Education

* Ghent University - PhD in eco-evolutionary dynamics, 2015
* Antwerp University - MS in evolutionary biology, 2010 (Magna Cum Laude)
* Antwerp University - BS in biology, 2008 (Cum Laude)

### Online Courses

* [Machine Learning](/files/Coursera_machine_learning.pdf) by Andrew Ng, - Stanford Online (Coursera)
* [R for data science](/figs/udemy_R_data_science.jpg) by Kirill Eremenko, - Udemy
* [Python Data Scientist track](https://www.datacamp.com/statement-of-accomplishment/track/44a5321ee748768340d8691ca3964cf9bf11eedc) by various teachers, - Datacamp
* [Python Programmer track](https://www.datacamp.com/statement-of-accomplishment/track/2f4f712243746878e61b9fd60e6bcb695b205ac0) by various teachers, - Datacamp
* [AI for everyone](https://www.coursera.org/account/accomplishments/verify/2MQG95D545NY) by Andrew Ng, - Deeplearning.ai (Coursera)
* [Reinforcement Learning specialization](https://www.coursera.org/account/accomplishments/specialization/UUAXXX9DGD5Q) by University of Alberta, - Coursera

### Publications

1. **Jeroen Boeye**, Justin M.J. Travis, Robby Stoks, Dries Bonte (2013) [More rapid climate change promotes evolutionary rescue through selection for increased dispersal distance.](http://onlinelibrary.wiley.com/doi/10.1111/eva.12004/full) *Evolutionary Applications* 2013, 6(2).

2. **Jeroen Boeye**, Alexander Kubisch, Dries Bonte (2014) [Habitat structure mediates spatial segregation and therefore coexistence.](https://link.springer.com/article/10.1007/s10980-014-0010-6) *Landscape Ecology* 2014, 29(4).

3. Jasmijn Hillaert, **Jeroen Boeye**, Robby Stoks, Dries Bonte (2015) [The evolution of thermal performance can constrain dispersal during range shifting.](http://www.tandfonline.com/doi/abs/10.1080/17513758.2015.1078503) *Journal of Biological Dynamics* 2015, 9(1).

4. Raoul Van Damme, Katrien Wijnrocx, **Jeroen Boeye**, Kathleen Huyghe, Stefan Van Dongen (2015) [Digit ratios in two lacertid lizards: sexual dimorphism and morphological and physiological correlates](https://link.springer.com/article/10.1007/s00435-015-0275-6) *Zoomorphology* 2015, 134(4).

5. Katrien H. P. Van Petegem, **Jeroen Boeye**, Robby Stoks, Dries Bonte (2016) [Spatial Selection and Local Adaptation Jointly Shape Life-History Evolution during Range Expansion.](http://www.journals.uchicago.edu/doi/abs/10.1086/688666#fn2) *Journal of Biological Dynamics* 2016, 188(5).

### Interests

* I [participated](https://2016.halite.io/user.php?userID=4991) in the [2016 Halite AI challenge](https://2016.halite.io/index.php) using a Python bot.
* [Football](/figs/football.jpg)
* Running
* Cycling
