baseURL = "https://jeroenboeye.com"
title = "Jeroen Boeye"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

disqusShortname = "jeroenboeye"
googleAnalytics = "UA-108004942-1"

Paginate = 5
preserveTaxonomyNames = true
enableEmoji = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Language Configuration
defaultContentLanguage = "en"

[params.info]
description = "Data scientist"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "JeroenBoeye"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = false
hideSocialMenu = false
showReadingTime = true

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "JeroenBoeye" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "jeroenboeye@gmail.com"
github = "jeroenboeye"
linkedin = "jeroen-boeye-b61320b3"
twitter = "JeroenBoeye"

[params.social.config]
platforms = ["email","twitter","github","linkedin"]

[taxonomies]
author = "Jeroen Boeye"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1